source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'SwiftyLocalizableViews_Example' do
  	pod "SwiftyLocalizableViews", :path => "../"
end

target 'SwiftyLocalizableViews_Tests' do
	pod "SwiftyLocalizableViews", :path => "../"
	pod 'Quick', :git => 'https://github.com/Quick/Quick', :branch => 'swift-3.0'
	pod 'Nimble', :git => 'https://github.com/Quick/Nimble'
end
